// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOO6tUEQauFNqx2emQzmXYRuYNMMV3Aec',
    appId: '1:913402740291:web:8c5b26894783d083121ef6',
    messagingSenderId: '913402740291',
    projectId: 'robolearn-8de10',
    authDomain: 'robolearn-8de10.firebaseapp.com',
    storageBucket: 'robolearn-8de10.firebasestorage.app',
    measurementId: 'G-S17F3R8LGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBznkIecUOSWWa2v0ubBZkhGx07NYKi348',
    appId: '1:913402740291:android:af9339f47fa8239b121ef6',
    messagingSenderId: '913402740291',
    projectId: 'robolearn-8de10',
    storageBucket: 'robolearn-8de10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbKhudyWP21W94lhUxq9FNXFaNP4kecPI',
    appId: '1:913402740291:ios:0f1356fad52e4169121ef6',
    messagingSenderId: '913402740291',
    projectId: 'robolearn-8de10',
    storageBucket: 'robolearn-8de10.firebasestorage.app',
    iosBundleId: 'com.example.robolearn',
  );

}